apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apiweb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apiweb
        tier: frontend
        cversion: "5"
    spec:
      containers:
      - image: tilen/demo-svc-web
        name: apiweb
        ports:
        - containerPort: 3000
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
          - name: MONGO_HOST
            valueFrom:
              secretKeyRef:
                name: mongo-db-secret-watch
                key: connstring.txt
          - name: NODE_ENV
            value: "prod"
          - name: LOGSTASH_HOST
            value: "log.tomakic.com"
