apiVersion: v1
kind: Service
metadata:
  name: apitwitter
spec:
  selector:
    app: apitwitter
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: LoadBalancer
